### ISSUE TITLE
Always shows the home page

### ISSUE THREAD

**Issue by zeeshanworkplains** [6o6o/sci-journal-mgr#1]
What is the purpose of this logic and it always executes the else part?

$all = $page + $assist;
unset($all['home']);
if(isset($all[$path])) {
	foreach($param as $k => $val) {
		if(!$val) $val = ucfirst($k);
		else if($i++) {
			if(!$prefix && !empty($_GET[$k])) $prefix[] = $val;
			continue;
		}
		if(!empty($_GET[$k])) $prefix[] = $val.' '.$_GET[$k];
	}
	if(!$prefix) $prefix[] = $all[$path] ? $all[$path] : ucfirst($path);
} else $path = 'home';

**Comment by 6o6o** [comment]
The condition checks if the requested path exists in either of top navigation menus. If it doesn't, it redirects you to homepage. To allow arbitrary pages replace the last line with
```
else if(!$path) $path = 'home';
```
You may get rid of the `else` part entirely, but then the root page `/` won't match your homepage.

The code inside the condition just does title composition.

Hope this helps.

**Comment by zeeshanworkplains** [comment]
Buddy when i replace the else part with your provided else if code, its not showing home page as well.

**Comment by zeeshanworkplains** [comment]
According to my understanding, $all array will never ever contains the $path. so if (isset($all[$path]))  will be always be false and else will get executed. And the same thing is happening.

**Comment by zeeshanworkplains** [comment]
Ok, one thing which might be the issue, that I'm running it on my local machine so I've a folder named journal. means the complete url looks like.... "localhost/journal/home"

**Comment by zeeshanworkplains** [comment]
Got the issue, the problem was the regex.

**Comment by 6o6o** [comment]
Yes, it strips the first level of the URL path component. You may need to adjust it on localhost.

Closing the issue if it's resolved.
